### ISSUE TITLE
method 关键字声明无效

### ISSUE THREAD

**Issue by lkqongit** [sunsgneayo/annotation#1]
```
@RequestMapping(methods="GET , POST" , path="/api/json")
```

#### methods 关键字的声明为post,  但postman get 请求还能获得正确响应，是否是我的操作有问题？

**Comment by sunsgneayo** [comment]
从代码上看您声明了`GET`,`POST`两种请求方式

**Comment by sunsgneayo** [comment]
@RequestMapping(methods="GET , POST" , path="/api/json")声明两种请求方式
