### ISSUE TITLE
同一个action是否可以支持多个路由请求

### ISSUE THREAD

**Issue by chenliq** [sunsgneayo/annotation#2]
比如：

    #[RequestMapping(methods: 'DELETE', path: '/admin/admin-role/{id}')]
    #[RequestMapping(methods: 'DELETE', path: '/admin/admin-roles')]
    public function delete(Request $request, string $ids = ''): Response
    {
        // do something
    }
删除的方法，如果单条记录，通过路径传参，如果是指删除，路径不一样，希望通过BODY传参，因此路由不一样

**Comment by sunsgneayo** [comment]
欢迎pr💪

**Comment by sunsgneayo** [comment]
下一个版本发布
